# Generated by Django 5.2 on 2025-04-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_file_post_image_post_alter_file_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blogs.post",
            ),
        ),
    ]
