# Generated by Django 5.2 on 2025-04-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="blogs.post",
            ),
        ),
    ]
